# Generated by Django 2.2.1 on 2019-08-27 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_stamp', models.DateField(default=datetime.date.today)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.Customer')),
            ],
        ),
    ]
