# Generated by Django 2.2.1 on 2019-08-27 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_of_issue', models.DateField(default=datetime.date.today)),
                ('cur_rewards', models.IntegerField(default=0)),
                ('max_red', models.IntegerField(default=0)),
            ],
        ),
    ]
