# Generated by Django 2.2.1 on 2019-08-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cur_rewards',
            new_name='current_rewards',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_of_issue',
            new_name='date_of_creation',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='max_red',
            new_name='max_redemption',
        ),
    ]
